# -*- coding: utf-8 -*-
"""TeleWeather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/185rbC1KQax7uBOjhE0zBiOBouPvS3Pow
"""

!pip install requests
!pip install pyTelegramBotAPI
import requests
import telebot

url = 'http://api.openweathermap.org/data/2.5/weather'
api_weather = '4e7e7b9a3211985b75f046d1e55b870e'
api_telegram = '1272021345:AAEk8pnNi-awkLiQ_x1crIdP0GhE6O33t_8'

#"lat":48.7194,"lon":44.5018,"country":"RU"
#https://api.openweathermap.org/data/2.5/onecall/timemachine?lat=48.7194&lon=44.5018&dt=1608742487&appid=4e7e7b9a3211985b75f046d1e55b870e
bot = telebot.TeleBot(api_telegram)

@bot.message_handler(commands=['start'])
def welcome(message):
  #sti = open('welcome.png', 'rb')
  #bot.send_sticker(message.chat.id) #,sti
  bot.send_message(message.chat.id, 'Добро пожаловать, ' + str(message.from_user.username) + ',' + '\n' +
  'Напиши мне название твоего города а я тебе информацию о погоде в твоем городе!')



@bot.message_handler(content_types=['text'])
def weather_send(message):
  #dateVchara = -1
  #dateSegodna = 0 
  #'dt': dateSegodna+86400,
  s_city = message.text

  try:
    #if(date = zav )
    params = {'APPID': api_weather, 'q': s_city, 'dt':+121604801, 'units': 'metric'}
    
    result = requests.get(url, params=params)
    weather = result.json()
    

    bot.send_message(message.chat.id, "В городе " + str(weather["name"]) + " температура " + str(float(weather["main"]['temp'])) + "\n" + 
    "Максимальная температура " + str(float(weather['main']['temp_max'])) + "\n" + 
    "дата" + str(weather['dt']) + "\n" + 
    "Минимальная температура " + str(float(weather['main']['temp_min'])) + "\n" + 
    "Скорость ветра " + str(float(weather['wind']['speed'])) + "\n" + 
    "Давление " + str(float(weather['main']['pressure'])) + "\n" + 
    "Влажность " + str(float(weather['main']['humidity'])) + "\n" + 
    "Видимость " + str(weather['visibility']) + "метров"+ "\n" + 
    "Описание " + str(weather['weather'][0]["description"]) + "\n")

    if weather["main"]['temp'] < 10:
      bot.send_message(message.chat.id, "Сейчас холодно!")
    elif weather["main"]['temp'] < 20:
      bot.send_message(message.chat.id, "Сейчас прохладно!")
    elif weather["main"]['temp'] > 38:
      bot.send_message(message.chat.id, "Сейчас жарко!")
    else:
      bot.send_message(message.chat.id, "Сейчас отличная температура!")

  except:
    bot.send_message(message.chat.id, "Город " + s_city + " не найден")


if __name__ == '__main__':
  bot.polling(none_stop=True)